//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDPServiceWPFClient.HelloService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagePost", Namespace="http://schemas.datacontract.org/2004/07/HelloCompLibrary")]
    [System.SerializableAttribute()]
    public partial class MessagePost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDetails {
            get {
                return this.MessageDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDetailsField, value) != true)) {
                    this.MessageDetailsField = value;
                    this.RaisePropertyChanged("MessageDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.IHello")]
    public interface IHello {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHello/PostMessages")]
        void PostMessages(UDPServiceWPFClient.HelloService.MessagePost message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IHello/PostMessages")]
        System.Threading.Tasks.Task PostMessagesAsync(UDPServiceWPFClient.HelloService.MessagePost message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/Greet", ReplyAction="http://tempuri.org/IHello/GreetResponse")]
        string Greet(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/Greet", ReplyAction="http://tempuri.org/IHello/GreetResponse")]
        System.Threading.Tasks.Task<string> GreetAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloChannel : UDPServiceWPFClient.HelloService.IHello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloClient : System.ServiceModel.ClientBase<UDPServiceWPFClient.HelloService.IHello>, UDPServiceWPFClient.HelloService.IHello {
        
        public HelloClient() {
        }
        
        public HelloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PostMessages(UDPServiceWPFClient.HelloService.MessagePost message) {
            base.Channel.PostMessages(message);
        }
        
        public System.Threading.Tasks.Task PostMessagesAsync(UDPServiceWPFClient.HelloService.MessagePost message) {
            return base.Channel.PostMessagesAsync(message);
        }
        
        public string Greet(string name) {
            return base.Channel.Greet(name);
        }
        
        public System.Threading.Tasks.Task<string> GreetAsync(string name) {
            return base.Channel.GreetAsync(name);
        }
    }
}
