//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloCompLibrary
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagePost", Namespace="http://schemas.datacontract.org/2004/07/HelloCompLibrary")]
    public partial class MessagePost : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageDetailsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDetails
        {
            get
            {
                return this.MessageDetailsField;
            }
            set
            {
                this.MessageDetailsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHello")]
public interface IHello
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/PostMessages", ReplyAction="http://tempuri.org/IHello/PostMessagesResponse")]
    void PostMessages(HelloCompLibrary.MessagePost message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/PostMessages", ReplyAction="http://tempuri.org/IHello/PostMessagesResponse")]
    System.Threading.Tasks.Task PostMessagesAsync(HelloCompLibrary.MessagePost message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/Greet", ReplyAction="http://tempuri.org/IHello/GreetResponse")]
    string Greet(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHello/Greet", ReplyAction="http://tempuri.org/IHello/GreetResponse")]
    System.Threading.Tasks.Task<string> GreetAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHelloChannel : IHello, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HelloClient : System.ServiceModel.ClientBase<IHello>, IHello
{
    
    public HelloClient()
    {
    }
    
    public HelloClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HelloClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void PostMessages(HelloCompLibrary.MessagePost message)
    {
        base.Channel.PostMessages(message);
    }
    
    public System.Threading.Tasks.Task PostMessagesAsync(HelloCompLibrary.MessagePost message)
    {
        return base.Channel.PostMessagesAsync(message);
    }
    
    public string Greet(string name)
    {
        return base.Channel.Greet(name);
    }
    
    public System.Threading.Tasks.Task<string> GreetAsync(string name)
    {
        return base.Channel.GreetAsync(name);
    }
}
